### PR TITLE
docs(contributing): Added draft structure for contributing.md

### PR DESCRIPTION
**Pull request by shivaylamba**
Fixes : #55 ( Typo in the docs)
Addresses  : #51  => Created a draft contributing.md

### CODE REVIEW

**Comment by shivaylamba** [comment]
@jgolden17 Can you please review

**Comment by jgolden17** [comment]
> @jgolden17 Can you please review

looking now

**Comment by shivaylamba** [comment]
@jgolden17 I will have to look into lerna

**Comment by shivaylamba** [comment]
@jgolden17 So do we need to include an installation/usage guide for Parrot using lerna?

**Comment by jgolden17** [comment]
> @jgolden17 So do we need to include an installation/usage guide for Parrot using lerna?

If you've got the time I'd like to at least get a section about creating the release release.  We can take that whole section out of one-app-cli and use it here.

Otherwise we can follow up this PR with another.

**Pull request merged**
