### PR TITLE
chore(travis): configure to deploy on tag

### PR DESCRIPTION
**Pull request by jgolden17**
Configure travis to initiate deployment whenever a new tag is created.

### CODE REVIEW

**Comment by nellyk** [comment]
Can we look at using[ `semantic-release`](https://github.com/semantic-release/semantic-release) a reference PR is https://github.com/semantic-release/semantic-release

**Comment by nellyk** [comment]
> Can we look at using[ `semantic-release`](https://github.com/semantic-release/semantic-release) instead. Reference PR is https://github.com/semantic-release/semantic-release

Just released this is lerna, would you like to do something similar as to what we are doing on `one-app-cli`

**Comment by jgolden17** [comment]
> > Can we look at using[ `semantic-release`](https://github.com/semantic-release/semantic-release) instead. Reference PR is https://github.com/semantic-release/semantic-release
> 
> Just released this is lerna, would you like to do something similar as to what we are doing on `one-app-cli`

If I'm understanding the one-app-cli process correctly, travis will trigger a job anytime that master is updated, if the latest commit is of type "chore(release): ..." then lernaDeploy.js will kick off a release. lerna will handle bumping the version and tagging the repo.  Is this correct?

**Comment by mtomcal** [comment]
Here is a link to the release process for one-app-cli: https://github.com/americanexpress/one-app-cli/blob/master/CONTRIBUTING.md#creating-a-one-app-cli-new-release

**Comment by nellyk** [comment]
> lerna will handle bumping the version and tagging the repo. Is this correct

Yes this is true. Thank you for sharing the details @mtomcal

**Comment by jgolden17** [comment]
Awesome. Thanks for the info.  I'll go with that.

**Pull request closed without merging**
