### PR TITLE
chore(release): 4.1.1

### PR DESCRIPTION
**Pull request by ferrettin**
#58

### CODE REVIEW

**Comment by nellyk** [comment]
@ferrettin Thank you for contribution, looks like you're to create a new release, to achieve this can you please follow this steps so that the changelogs are also updated

- Run `npm run lerna:version ` locally from your release branch. This would push your release changes(changelog and tags) to the branch on github.
- Create a pull request from your branch to the master branch with your changes.
- Once the changes are approved ensure you merge the changes and provide the commit message for the merge as chore(release) : 1.9.7 ensure you follow this convention otherwise the deployment will not be executed.
- Once this is merged to master a deployment would be initiated on the master branch and all packages that changed would be released to npm.

**Comment by ferrettin** [comment]
hey @nellyk those steps were followed in the making of this PR. Are any further changes needed?

**Comment by nellyk** [comment]
@ferrettin can't seem to see the changelogs though?

**Comment by jgolden17** [comment]
> @ferrettin can't seem to see the changelogs though?

There seems to be an issue with changelogs not being generated for this project.  Will need to look at this separately.

**Pull request closed without merging**
